const EMOJI_CATEGORIES = {
  smileys: {
    name: "Smileys & Emotion",
    emojis: [
      { emoji: "😀", name: "grinning" },
      { emoji: "😃", name: "smiley" },
      { emoji: "😄", name: "smile" },
      { emoji: "😁", name: "grin" },
      { emoji: "😆", name: "laughing" },
      { emoji: "😅", name: "sweat_smile" },
      { emoji: "🤣", name: "rofl" },
      { emoji: "😂", name: "joy" },
      { emoji: "🙂", name: "slightly_smiling_face" },
      { emoji: "🙃", name: "upside_down_face" },
      { emoji: "😉", name: "wink" },
      { emoji: "😊", name: "blush" },
      { emoji: "😇", name: "innocent" },
      { emoji: "🥰", name: "smiling_face_with_three_hearts" },
      { emoji: "😍", name: "heart_eyes" },
      { emoji: "🤩", name: "star_struck" },
      { emoji: "😘", name: "kissing_heart" },
      { emoji: "😐", name: "neutral_face" },
      { emoji: "😑", name: "expressionless" },
      { emoji: "😴", name: "sleeping" },
      { emoji: "🤔", name: "thinking" },
    ],
  },
  food: {
    name: "Food & Drinks",
    emojis: [
      { emoji: "🍎", name: "apple" },
      { emoji: "🍊", name: "tangerine" },
      { emoji: "🍋", name: "lemon" },
      { emoji: "🍌", name: "banana" },
      { emoji: "🍉", name: "watermelon" },
      { emoji: "🍇", name: "grapes" },
      { emoji: "🍓", name: "strawberry" },
      { emoji: "🫐", name: "blueberries" },
      { emoji: "🍈", name: "melon" },
      { emoji: "🍒", name: "cherries" },
      { emoji: "🥭", name: "mango" },
      { emoji: "🍑", name: "peach" },
      { emoji: "🍍", name: "pineapple" },
      { emoji: "🥥", name: "coconut" },
      { emoji: "🥝", name: "kiwi_fruit" },
      { emoji: "🍞", name: "bread" },
      { emoji: "🥖", name: "baguette_bread" },
      { emoji: "🧀", name: "cheese" },
      { emoji: "🥚", name: "egg" },
      { emoji: "🍯", name: "honey_pot" },
      { emoji: "☕", name: "coffee" },
      { emoji: "🫖", name: "teapot" },
      { emoji: "🧃", name: "beverage_box" },
      { emoji: "🥛", name: "milk_glass" },
    ],
  },
  nature: {
    name: "Nature & Weather",
    emojis: [
      { emoji: "🌱", name: "seedling" },
      { emoji: "🌿", name: "herb" },
      { emoji: "🍀", name: "four_leaf_clover" },
      { emoji: "🌸", name: "cherry_blossom" },
      { emoji: "🌺", name: "hibiscus" },
      { emoji: "🌻", name: "sunflower" },
      { emoji: "🌷", name: "tulip" },
      { emoji: "🌹", name: "rose" },
      { emoji: "🌲", name: "evergreen_tree" },
      { emoji: "🌳", name: "deciduous_tree" },
      { emoji: "🌴", name: "palm_tree" },
      { emoji: "🌵", name: "cactus" },
      { emoji: "☀️", name: "sunny" },
      { emoji: "🌤️", name: "partly_sunny" },
      { emoji: "⛅", name: "cloud" },
      { emoji: "🌧️", name: "cloud_with_rain" },
      { emoji: "⛈️", name: "cloud_with_lightning_and_rain" },
      { emoji: "❄️", name: "snowflake" },
    ],
  },
  activities: {
    name: "Activities & Sports",
    emojis: [
      { emoji: "⚽", name: "soccer" },
      { emoji: "🏀", name: "basketball" },
      { emoji: "🏈", name: "football" },
      { emoji: "⚾", name: "baseball" },
      { emoji: "🥎", name: "softball" },
      { emoji: "🎾", name: "tennis" },
      { emoji: "🏐", name: "volleyball" },
      { emoji: "🏓", name: "ping_pong" },
      { emoji: "🎱", name: "8ball" },
      { emoji: "🪀", name: "yo_yo" },
      { emoji: "🎯", name: "dart" },
      { emoji: "🎲", name: "game_die" },
      { emoji: "🎮", name: "video_game" },
      { emoji: "🎸", name: "guitar" },
      { emoji: "🎹", name: "musical_keyboard" },
      { emoji: "🥁", name: "drum" },
      { emoji: "🎵", name: "musical_note" },
      { emoji: "🎶", name: "notes" },
      { emoji: "🎤", name: "microphone" },
      { emoji: "🎧", name: "headphones" },
      { emoji: "🎨", name: "art" },
    ],
  },
  travel: {
    name: "Travel & Places",
    emojis: [
      { emoji: "🌍", name: "earth_africa" },
      { emoji: "🌎", name: "earth_americas" },
      { emoji: "🌏", name: "earth_asia" },
      { emoji: "🗺️", name: "world_map" },
      { emoji: "🏔️", name: "mountain_snow" },
      { emoji: "⛰️", name: "mountain" },
      { emoji: "🏕️", name: "camping" },
      { emoji: "🏖️", name: "beach_umbrella" },
      { emoji: "🏜️", name: "desert" },
      { emoji: "🏝️", name: "desert_island" },
      { emoji: "🏞️", name: "national_park" },
      { emoji: "🌋", name: "volcano" },
      { emoji: "🗻", name: "mount_fuji" },
      { emoji: "🏟️", name: "stadium" },
      { emoji: "🏛️", name: "classical_building" },
      { emoji: "🕌", name: "mosque" },
      { emoji: "🏗️", name: "building_construction" },
      { emoji: "🏘️", name: "houses" },
      { emoji: "🏙️", name: "cityscape" },
      { emoji: "🏰", name: "castle" },
      { emoji: "🗼", name: "tokyo_tower" },
      { emoji: "🏠", name: "house" },
    ],
  },
  objects: {
    name: "Objects & Tools",
    emojis: [
      { emoji: "📱", name: "iphone" },
      { emoji: "💻", name: "computer" },
      { emoji: "🖥️", name: "desktop_computer" },
      { emoji: "⌨️", name: "keyboard" },
      { emoji: "🖱️", name: "computer_mouse" },
      { emoji: "🖨️", name: "printer" },
      { emoji: "📺", name: "tv" },
      { emoji: "📷", name: "camera" },
      { emoji: "📹", name: "video_camera" },
      { emoji: "🔍", name: "mag" },
      { emoji: "💡", name: "bulb" },
      { emoji: "🔦", name: "flashlight" },
      { emoji: "🕯️", name: "candle" },
      { emoji: "🪔", name: "diya_lamp" },
      { emoji: "📚", name: "books" },
      { emoji: "📖", name: "book" },
      { emoji: "📝", name: "memo" },
      { emoji: "✏️", name: "pencil2" },
      { emoji: "🖊️", name: "pen" },
      { emoji: "📐", name: "triangular_ruler" },
      { emoji: "🔑", name: "key" },
      { emoji: "💎", name: "gem" },
    ],
  },
  celebrations: {
    name: "Celebrations & Achievements",
    emojis: [
      { emoji: "🎉", name: "tada" },
      { emoji: "🎊", name: "confetti_ball" },
      { emoji: "🎈", name: "balloon" },
      { emoji: "🎁", name: "gift" },
      { emoji: "🏆", name: "trophy" },
    ],
  },
  symbols: {
    name: "Symbols & Signs",
    emojis: [
      { emoji: "❤️", name: "heart" },
      { emoji: "💚", name: "green_heart" },
      { emoji: "💙", name: "blue_heart" },
      { emoji: "💜", name: "purple_heart" },
      { emoji: "🤍", name: "white_heart" },
      { emoji: "⭐", name: "star" },
      { emoji: "🌟", name: "star2" },
      { emoji: "✨", name: "sparkles" },
      { emoji: "💫", name: "dizzy" },
      { emoji: "🔥", name: "fire" },
      { emoji: "💯", name: "100" },
      { emoji: "✅", name: "white_check_mark" },
      { emoji: "❌", name: "x" },
      { emoji: "⚡", name: "zap" },
      { emoji: "💥", name: "boom" },
      { emoji: "☮️", name: "peace_symbol" },
      { emoji: "☪️", name: "star_and_crescent" },
      { emoji: "🕎", name: "menorah" },
      { emoji: "☯️", name: "yin_yang" },
      { emoji: "🔯", name: "six_pointed_star" },
      { emoji: "♾️", name: "infinity" },
    ],
  },
  flags: {
    name: "Flags & Countries",
    emojis: [
      { emoji: "🏁", name: "checkered_flag" },
      { emoji: "🏳️", name: "white_flag" },
      { emoji: "🏴", name: "black_flag" },
      { emoji: "🇦🇫", name: "afghanistan" },
      { emoji: "🇦🇱", name: "albania" },
      { emoji: "🇩🇿", name: "algeria" },
      { emoji: "🇦🇩", name: "andorra" },
      { emoji: "🇦🇴", name: "angola" },
      { emoji: "🇦🇬", name: "antigua_barbuda" },
      { emoji: "🇦🇷", name: "argentina" },
      { emoji: "🇦🇲", name: "armenia" },
      { emoji: "🇦🇺", name: "australia" },
      { emoji: "🇦🇹", name: "austria" },
      { emoji: "🇦🇿", name: "azerbaijan" },
      { emoji: "🇧🇸", name: "bahamas" },
      { emoji: "🇧🇭", name: "bahrain" },
      { emoji: "🇧🇩", name: "bangladesh" },
      { emoji: "🇧🇧", name: "barbados" },
      { emoji: "🇧🇾", name: "belarus" },
      { emoji: "🇧🇪", name: "belgium" },
      { emoji: "🇧🇿", name: "belize" },
      { emoji: "🇧🇯", name: "benin" },
      { emoji: "🇧🇹", name: "bhutan" },
      { emoji: "🇧🇴", name: "bolivia" },
      { emoji: "🇧🇦", name: "bosnia_herzegovina" },
      { emoji: "🇧🇼", name: "botswana" },
      { emoji: "🇧🇷", name: "brazil" },
      { emoji: "🇧🇳", name: "brunei" },
      { emoji: "🇧🇬", name: "bulgaria" },
      { emoji: "🇧🇫", name: "burkina_faso" },
      { emoji: "🇧🇮", name: "burundi" },
      { emoji: "🇰🇭", name: "cambodia" },
      { emoji: "🇨🇲", name: "cameroon" },
      { emoji: "🇨🇦", name: "canada" },
      { emoji: "🇨🇻", name: "cape_verde" },
      { emoji: "🇨🇫", name: "central_african_republic" },
      { emoji: "🇹🇩", name: "chad" },
      { emoji: "🇨🇱", name: "chile" },
      { emoji: "🇨🇳", name: "china" },
      { emoji: "🇨🇴", name: "colombia" },
      { emoji: "🇰🇲", name: "comoros" },
      { emoji: "🇨🇬", name: "congo_brazzaville" },
      { emoji: "🇨🇩", name: "congo_kinshasa" },
      { emoji: "🇨🇷", name: "costa_rica" },
      { emoji: "🇭🇷", name: "croatia" },
      { emoji: "🇨🇺", name: "cuba" },
      { emoji: "🇨🇾", name: "cyprus" },
      { emoji: "🇨🇿", name: "czech_republic" },
      { emoji: "🇩🇰", name: "denmark" },
      { emoji: "🇩🇯", name: "djibouti" },
      { emoji: "🇩🇲", name: "dominica" },
      { emoji: "🇩🇴", name: "dominican_republic" },
      { emoji: "🇪🇨", name: "ecuador" },
      { emoji: "🇪🇬", name: "egypt" },
      { emoji: "🇸🇻", name: "el_salvador" },
      { emoji: "🇬🇶", name: "equatorial_guinea" },
      { emoji: "🇪🇷", name: "eritrea" },
      { emoji: "🇪🇪", name: "estonia" },
      { emoji: "🇸🇿", name: "swaziland" },
      { emoji: "🇪🇹", name: "ethiopia" },
      { emoji: "🇫🇯", name: "fiji" },
      { emoji: "🇫🇮", name: "finland" },
      { emoji: "🇫🇷", name: "france" },
      { emoji: "🇬🇦", name: "gabon" },
      { emoji: "🇬🇲", name: "gambia" },
      { emoji: "🇬🇪", name: "georgia" },
      { emoji: "🇩🇪", name: "germany" },
      { emoji: "🇬🇭", name: "ghana" },
      { emoji: "🇬🇷", name: "greece" },
      { emoji: "🇬🇩", name: "grenada" },
      { emoji: "🇬🇹", name: "guatemala" },
      { emoji: "🇬🇳", name: "guinea" },
      { emoji: "🇬🇼", name: "guinea_bissau" },
      { emoji: "🇬🇾", name: "guyana" },
      { emoji: "🇭🇹", name: "haiti" },
      { emoji: "🇭🇳", name: "honduras" },
      { emoji: "🇭🇺", name: "hungary" },
      { emoji: "🇮🇸", name: "iceland" },
      { emoji: "🇮🇳", name: "india" },
      { emoji: "🇮🇩", name: "indonesia" },
      { emoji: "🇮🇷", name: "iran" },
      { emoji: "🇮🇶", name: "iraq" },
      { emoji: "🇮🇪", name: "ireland" },
      { emoji: "🇮🇱", name: "israel" },
      { emoji: "🇮🇹", name: "italy" },
      { emoji: "🇨🇮", name: "cote_divoire" },
      { emoji: "🇯🇲", name: "jamaica" },
      { emoji: "🇯🇵", name: "japan" },
      { emoji: "🇯🇴", name: "jordan" },
      { emoji: "🇰🇿", name: "kazakhstan" },
      { emoji: "🇰🇪", name: "kenya" },
      { emoji: "🇰🇮", name: "kiribati" },
      { emoji: "🇰🇼", name: "kuwait" },
      { emoji: "🇰🇬", name: "kyrgyzstan" },
      { emoji: "🇱🇦", name: "laos" },
      { emoji: "🇱🇻", name: "latvia" },
      { emoji: "🇱🇧", name: "lebanon" },
      { emoji: "🇱🇸", name: "lesotho" },
      { emoji: "🇱🇷", name: "liberia" },
      { emoji: "🇱🇾", name: "libya" },
      { emoji: "🇱🇮", name: "liechtenstein" },
      { emoji: "🇱🇹", name: "lithuania" },
      { emoji: "🇱🇺", name: "luxembourg" },
      { emoji: "🇲🇬", name: "madagascar" },
      { emoji: "🇲🇼", name: "malawi" },
      { emoji: "🇲🇾", name: "malaysia" },
      { emoji: "🇲🇻", name: "maldives" },
      { emoji: "🇲🇱", name: "mali" },
      { emoji: "🇲🇹", name: "malta" },
      { emoji: "🇲🇭", name: "marshall_islands" },
      { emoji: "🇲🇷", name: "mauritania" },
      { emoji: "🇲🇺", name: "mauritius" },
      { emoji: "🇲🇽", name: "mexico" },
      { emoji: "🇫🇲", name: "micronesia" },
      { emoji: "🇲🇩", name: "moldova" },
      { emoji: "🇲🇨", name: "monaco" },
      { emoji: "🇲🇳", name: "mongolia" },
      { emoji: "🇲🇪", name: "montenegro" },
      { emoji: "🇲🇦", name: "morocco" },
      { emoji: "🇲🇿", name: "mozambique" },
      { emoji: "🇲🇲", name: "myanmar" },
      { emoji: "🇳🇦", name: "namibia" },
      { emoji: "🇳🇷", name: "nauru" },
      { emoji: "🇳🇵", name: "nepal" },
      { emoji: "🇳🇱", name: "netherlands" },
      { emoji: "🇳🇿", name: "new_zealand" },
      { emoji: "🇳🇮", name: "nicaragua" },
      { emoji: "🇳🇪", name: "niger" },
      { emoji: "🇳🇬", name: "nigeria" },
      { emoji: "🇰🇵", name: "north_korea" },
      { emoji: "🇲🇰", name: "macedonia" },
      { emoji: "🇳🇴", name: "norway" },
      { emoji: "🇴🇲", name: "oman" },
      { emoji: "🇵🇰", name: "pakistan" },
      { emoji: "🇵🇼", name: "palau" },
      { emoji: "🇵🇸", name: "palestinian_territories" },
      { emoji: "🇵🇦", name: "panama" },
      { emoji: "🇵🇬", name: "papua_new_guinea" },
      { emoji: "🇵🇾", name: "paraguay" },
      { emoji: "🇵🇪", name: "peru" },
      { emoji: "🇵🇭", name: "philippines" },
      { emoji: "🇵🇱", name: "poland" },
      { emoji: "🇵🇹", name: "portugal" },
      { emoji: "🇶🇦", name: "qatar" },
      { emoji: "🇷🇴", name: "romania" },
      { emoji: "🇷🇺", name: "russia" },
      { emoji: "🇷🇼", name: "rwanda" },
      { emoji: "🇼🇸", name: "samoa" },
      { emoji: "🇸🇲", name: "san_marino" },
      { emoji: "🇸🇹", name: "sao_tome_principe" },
      { emoji: "🇸🇦", name: "saudi_arabia" },
      { emoji: "🇸🇳", name: "senegal" },
      { emoji: "🇷🇸", name: "serbia" },
      { emoji: "🇸🇨", name: "seychelles" },
      { emoji: "🇸🇱", name: "sierra_leone" },
      { emoji: "🇸🇬", name: "singapore" },
      { emoji: "🇸🇰", name: "slovakia" },
      { emoji: "🇸🇮", name: "slovenia" },
      { emoji: "🇸🇧", name: "solomon_islands" },
      { emoji: "🇸🇴", name: "somalia" },
      { emoji: "🇿🇦", name: "south_africa" },
      { emoji: "🇰🇷", name: "south_korea" },
      { emoji: "🇸🇸", name: "south_sudan" },
      { emoji: "🇪🇸", name: "spain" },
      { emoji: "🇱🇰", name: "sri_lanka" },
      { emoji: "🇸🇩", name: "sudan" },
      { emoji: "🇸🇷", name: "suriname" },
      { emoji: "🇸🇪", name: "sweden" },
      { emoji: "🇨🇭", name: "switzerland" },
      { emoji: "🇸🇾", name: "syria" },
      { emoji: "🇹🇼", name: "taiwan" },
      { emoji: "🇹🇯", name: "tajikistan" },
      { emoji: "🇹🇿", name: "tanzania" },
      { emoji: "🇹🇭", name: "thailand" },
      { emoji: "🇹🇱", name: "timor_leste" },
      { emoji: "🇹🇬", name: "togo" },
      { emoji: "🇹🇴", name: "tonga" },
      { emoji: "🇹🇹", name: "trinidad_tobago" },
      { emoji: "🇹🇳", name: "tunisia" },
      { emoji: "🇹🇷", name: "turkey" },
      { emoji: "🇹🇲", name: "turkmenistan" },
      { emoji: "🇹🇻", name: "tuvalu" },
      { emoji: "🇺🇬", name: "uganda" },
      { emoji: "🇺🇦", name: "ukraine" },
      { emoji: "🇦🇪", name: "united_arab_emirates" },
      { emoji: "🇬🇧", name: "uk" },
      { emoji: "🇺🇸", name: "us" },
      { emoji: "🇺🇾", name: "uruguay" },
      { emoji: "🇺🇿", name: "uzbekistan" },
      { emoji: "🇻🇺", name: "vanuatu" },
      { emoji: "🇻🇦", name: "vatican_city" },
      { emoji: "🇻🇪", name: "venezuela" },
      { emoji: "🇻🇳", name: "vietnam" },
      { emoji: "🇾🇪", name: "yemen" },
      { emoji: "🇿🇲", name: "zambia" },
      { emoji: "🇿🇼", name: "zimbabwe" },
    ],
  },
};

export default EMOJI_CATEGORIES;
